// Load common functions
require('./common.js');

// Start of unwantedRecipes
console.info('Removing unwanted recipes...')

ServerEvents.recipes(event => {
    unwantedRecipes(event)
})

function unwantedRecipes(event) {

    event.remove({ output: '#forge:coins' })
    event.remove({ output: AE2('grindstone') })
    event.remove({ output: AE2('vibration_chamber') })
    event.remove({ output: AE2('inscriber') })
    event.remove({ output: AE2('quartz_glass') })
    event.remove({ output: CR('chromatic_compound') })
    event.remove({ input: '#forge:coins' })
    event.remove({ type: AE2('grinder') })
    event.remove({ type: TE('press') })
    event.remove({ id: /thermal:earth_charge\/.*/ })
    event.remove({ id: /thermal:machine\/smelter\/.*dust/ })
    event.remove({ id: /tconstruct:smeltery\/.*\/ore/ })
    event.remove({ id: "tconstruct:tables/tinkers_forge" })
    event.remove({ id: "tconstruct:tables/scorched_forge" })
    event.remove({ id: /ae2:tools\/paintballs.*/ })
    event.remove({ id: "grapplemod:repeller" })
    event.remove({ id: "grapplemod:forcefieldupgradeitem" })
    event.remove({ id: "grapplemod:rocketupgradeitem" })
    event.remove({ id: "grapplemod:rocketdoublemotorhook" })
    event.remove({ id: "grapplemod:magnethook" })
    event.remove({ id: "grapplemod:rockethook" })
    event.remove({ id: "randomium:duplicate" })
    event.remove({ id: "forbidden_arcanus:eternal_stella" })
    event.remove({ id: OC('miner/ores/redstone_ore') })
    event.remove({ id: OC('miner/ores/silver_ore') })
    event.remove({ id: MC('diorite') })
    event.remove({ id: MC('andesite') })
    event.remove({ id: MC('granite') })
    event.remove({ id: CR('mixing/brass_ingot') })
    event.remove({ id: 'thermal:compat/biomesoplenty/tree_extractor_bop_pink_cherry' })
    event.remove({ id: 'thermal:compat/biomesoplenty/tree_extractor_bop_white_cherry' })
    event.remove({ id: 'thermal:compat/biomesoplenty/tree_extractor_bop_fir' })
    event.remove({ id: TC('smeltery/melting/metal/gold/enchanted_apple') })
    event.remove({ id: CR('cutting/andesite_alloy') })
    event.remove({ id: TE('storage/beetroot_block') })
    event.remove({ id: TE('storage/potato_block') })
    event.remove({ id: TE('storage/apple_block') })
    event.remove({ output: Q('potato_crate') })
    event.remove({ output: Q('carrot_crate') })
    event.remove({ output: Q('beetroot_crate') })
    event.remove({ id: AE2('misc/grindstone_woodengear') })
    event.remove({ id: AE2('tools/misctools_entropy_manipulator') })
    event.remove({ id: TE('storage/carrot_block') })

    event.remove({ id: TE('fire_charge/invar_ingot_3') })
    event.remove({ id: TE('fire_charge/enderium_ingot_2') })
    event.remove({ id: TE('fire_charge/constantan_ingot_2') })
    event.remove({ id: TE('fire_charge/bronze_ingot_4') })
    event.remove({ id: TE('fire_charge/electrum_ingot_2') })
    event.remove({ id: TE('fire_charge/lumium_ingot_4') })
    event.remove({ id: TE('fire_charge/signalum_ingot_4') })

    // event.remove({ input: '#forge:ores/redstone' })
    // event.remove({ input: '#create:crushed_ores' })
    // event.remove({ input: '#forge:ores/tin' })
    // event.remove({ input: '#forge:ores/silver' })
    // event.remove({ output: '#forge:plates/tin' })
    // event.remove({ output: '#forge:plates/silver' })
    // event.remove({ output: '#forge:gears/tin' })
    // event.remove({ output: '#forge:gears/silver' })

    event.remove({ id: TE('machine/pulverizer/pulverizer_cinnabar') })
    event.remove({ id: TE('machine/smelter/smelter_alloy_signalum') })
    event.remove({ id: TE('machine/smelter/smelter_alloy_lumium') })
    event.remove({ id: TE('machine/smelter/smelter_alloy_electrum') })
    event.remove({ id: TE('machine/smelter/smelter_alloy_enderium') })
    event.remove({ id: TE('machine/smelter/smelter_alloy_invar') })
    event.remove({ id: TE('machine/smelter/smelter_alloy_constantan') })
    event.remove({ id: TE('machine/smelter/smelter_alloy_bronze') })

    event.remove({ id: TE('compat/create/smelter_create_alloy_brass') })
    event.remove({ id: TE('compat/tconstruct/smelter_alloy_tconstruct_rose_gold_ingot') })
    event.remove({ id: TE('machine/pulverizer/pulverizer_ender_pearl') })
    event.remove({ id: TE('storage/electrum_block') })
    event.remove({ id: TE('storage/electrum_nugget_from_ingot') })
    event.remove({ id: TE('machine/pulverizer/pulverizer_electrum_ingot_to_dust') })
    event.remove({ id: TE('parts/electrum_gear') })
    event.remove({ id: AP('smelting/charcoal_block_from_logs_that_burn_smoking') })
    event.remove({ id: 'portality:generator' })

    // event.remove({ input: TE('signalum_dust'), output: TE('signalum_ingot') })
    // event.remove({ output: TE('signalum_dust'), input: TE('signalum_ingot') })

    event.remove({ output: TE('lightning_charge') })
    event.remove({ output: TE('ice_charge') })
    event.remove({ output: TE('earth_charge') })
    event.remove({ input: TE('lightning_charge') })
    event.remove({ input: TE('ice_charge') })
    event.remove({ input: TE('earth_charge') })

    // event.remove({ input: "forbidden_arcanus:edelwood_bucket" })
    // event.remove({ output: "forbidden_arcanus:edelwood_bucket" })

    // native_metals.forEach(e => {
    // 	event.remove({ type: MC("smelting"), input: F("#dusts/" + e) })
    // 	event.remove({ type: MC("blasting"), input: F("#dusts/" + e) })
    // 	event.remove({ type: TC("melting"), input: F("#dusts/" + e) })
    // })

    event.remove({ output: 'projectred_core:electrotine_generator' })
    event.remove({ output: 'projectred_core:sand_coal_comp' })
    event.remove({ output: 'projectred_core:boule' })
    event.remove({ output: 'projectred_core:silicon' })
    event.remove({ output: 'projectred_core:copper_coil' })
    event.remove({ output: 'projectred_core:iron_coil' })
    event.remove({ output: 'projectred_core:gold_coil' })
    event.remove({ output: 'projectred_core:electrotine_iron_comp' })
    event.remove({ output: 'projectred_core:infused_silicon' })
    event.remove({ output: 'projectred_core:energized_silicon' })
    event.remove({ output: 'projectred_core:electrotine_silicon' })

    event.remove({ input: 'projectred_core:electrotine_generator' })
    event.remove({ input: 'projectred_core:sand_coal_comp' })
    event.remove({ input: 'projectred_core:boule' })
    event.remove({ input: 'projectred_core:silicon' })
    event.remove({ input: 'projectred_core:copper_coil' })
    event.remove({ input: 'projectred_core:iron_coil' })
    event.remove({ input: 'projectred_core:gold_coil' })
    event.remove({ input: 'projectred_core:infused_silicon' })
    event.remove({ input: 'projectred_core:energized_silicon' })
    event.remove({ input: 'projectred_core:electrotine_silicon' })

    // No more FREE INDUSTRIAL IRON BLOCKS :(
    event.remove({ output: CR('industrial_iron_block'), type: 'minecraft:stonecutting' })

}