// priority: 0

console.info('Client script load phase...');

let MysteriousItemConversionCategory = java('com.simibubi.create.compat.jei.category.MysteriousItemConversionCategory')
let ConversionRecipe = java('com.simibubi.create.compat.jei.ConversionRecipe')

// rei显示神秘转化
MysteriousItemConversionCategory.RECIPES.add(ConversionRecipe.create('ae2:singularity', 'ae2:quantum_entangled_singularity'))
// MysteriousItemConversionCategory.RECIPES.add(ConversionRecipe.create('create:chromatic_compound', 'create:shadow_steel'))
// MysteriousItemConversionCategory.RECIPES.add(ConversionRecipe.create('create:chromatic_compound', 'create:refined_radiance'))


onEvent('rei.add.items', event => {
    event.add(Item.of('create:refined_radiance'));
    event.add(Item.of('create:shadow_steel'));
    event.add(Item.of('create:chromatic_compound'));
    event.add('thermal:ruby')
	  event.add('thermal:ruby_dust')
	  event.add('thermal:ruby_ore')
	  event.add('thermal:apatite_ore')
	  event.add('thermal:sapphire')
	  event.add('thermal:sapphire_dust')
	  event.add('thermal:sapphire_ore')
  })

  onEvent('jei.hide.items', event => {
    event.hide('ae2:facade')
    event.hide(`#buddycards:cards`)
    event.hide(`#buddycards:gummy_cards`)
    event.hide(`createdeco:zinc_coin`)
    event.hide(`createdeco:copper_coin`)
    event.hide(`createdeco:brass_coin`)
    event.hide(`createdeco:iron_coin`)
    event.hide(`createdeco:gold_coin`)
    event.hide(`createdeco:netherite_coin`)
    event.hide(`createdeco:cast_iron_coin`)
    event.hide(`createdeco:zinc_coinstack`)
    event.hide(`createdeco:copper_coinstack`)
    event.hide(`createdeco:brass_coinstack`)
    event.hide(`createdeco:iron_coinstack`)
    event.hide(`createdeco:gold_coinstack`)
    event.hide(`createdeco:netherite_coinstack`)
    event.hide(`createdeco:cast_iron_coinstack`)
    event.hide(`kubejs:trade_card_exchange_currencies_a`)
    event.hide(`createdeco:cast_iron_sheet`)
    event.hide(`createdeco:cast_iron_ingot`)
    event.hide(`create_dd:tin_ore`)
    event.hide(`create_dd:deepslate_tin_ore`)
    event.hide(`beyond_earth:nasa_workbench`)
    event.hide(`thermal:steel_coin`)
    event.hide(`thermal:rose_gold_coin`)
    event.hide(`thermal:iron_coin`)
    event.hide(`thermal:copper_coin`)
    event.hide(`thermal:netherite_coin`)
    event.hide(`thermal:tin_coin`)
    event.hide(`thermal:lead_coin`)
    event.hide(`thermal:nickel_coin`)
    event.hide(`thermal:bronze_coin`)
    event.hide(`thermal:electrum_coin`)
    event.hide(`thermal:invar_coin`)
    event.hide(`thermal:constantan_coin`)
    event.hide(`thermal:signalum_coin`)
    event.hide(`thermal:lumium_coin`)
    event.hide(`thermal:enderium_coin`)
    event.hide(`occultism:silver_ore`)
    event.hide(`occultism:silver_ore_deepslate`)
    event.hide(`#tconstruct:casts/single_use/coin`)
    event.hide(`#tconstruct:casts/multi_use/coin`)
    event.hide(`ae2:white_paint_ball`)
    event.hide(`ae2:orange_paint_ball`)
    event.hide(`ae2:light_blue_paint_ball`)
    event.hide(`ae2:lime_paint_ball`)
    event.hide(`ae2:pink_paint_ball`)
    event.hide(`ae2:gray_paint_ball`)
    event.hide(`ae2:light_gray_paint_ball`)
    event.hide(`ae2:cyan_paint_ball`)
    event.hide(`ae2:purple_paint_ball`)
    event.hide(`ae2:brown_paint_ball`)
    event.hide(`ae2:white_lumen_paint_ball`)
    event.hide(`ae2:orange_lumen_paint_ball`)
    event.hide(`ae2:magenta_lumen_paint_ball`)
    event.hide(`ae2:light_blue_lumen_paint_ball`)
    event.hide(`ae2:yellow_lumen_paint_ball`)
    event.hide(`ae2:lime_lumen_paint_ball`)
    event.hide(`ae2:pink_lumen_paint_ball`)
    event.hide(`ae2:gray_lumen_paint_ball`)
    event.hide(`ae2:light_gray_lumen_paint_ball`)
    event.hide(`ae2:cyan_lumen_paint_ball`)
    event.hide(`ae2:purple_lumen_paint_ball`)
    event.hide(`ae2:blue_lumen_paint_ball`)
    event.hide(`ae2:brown_lumen_paint_ball`)
    event.hide(`ae2:green_lumen_paint_ball`)
    event.hide(`ae2:red_lumen_paint_ball`)
    event.hide(`ae2:black_lumen_paint_ball`)
    event.hide(`darkerdepths:raw_silver`)
    event.hide(`darkerdepths:silver_ingot`)
    event.hide(`darkerdepths:raw_silver_block`)
    event.hide(`darkerdepths:silver_block`)
    event.hide(`thermal:tin_block`)
    event.hide(`vintageimprovements:tin_sheet`)
    event.hide(`thermal:iron_plate`)
    event.hide(`create_dd:raw_tin`)
    event.hide(`beyond_earth:iron_plate`)
    event.hide(`beyond_earth:iron_stick`)
    event.hide(`create_dd:raw_tin_block`)
    event.hide(`thermal:tin_plate`)
    event.hide(`thermal:tin_nugget`)
    event.hide(`thermal:tin_ingot`)
    event.hide(`occultism:silver_ingot`)
    event.hide(`occultism:silver_nugget`)
    event.hide(`occultism:silver_block`)
    event.hide(`thermal:charcoal_block`)
    event.hide(`quark:charcoal_block`)
    event.hide(`waterstrainer:strainer_survivalist_solid`)
    event.hide(`waterstrainer:strainer_survivalist_reinforced`)
    event.hide(`waterstrainer:strainer_fisherman_solid`)
    event.hide(`exchangers:bee_exchanger`)
    event.hide(`beyond_earth:nasa_workbench`)
  })