// priority: 0

console.info('Hello, World! (You will see this line every time client resources reload)')

onEvent('rei.add.items', event => {
    event.add(Item.of('create:refined_radiance'));
    event.add(Item.of('create:shadow_steel'));
    event.add(Item.of('create:chromatic_compound'));
    event.add('thermal:ruby')
	  event.add('thermal:ruby_dust')
	  event.add('thermal:ruby_ore')
	  event.add('thermal:apatite_ore')
	  event.add('thermal:sapphire')
	  event.add('thermal:sapphire_dust')
	  event.add('thermal:sapphire_ore')
  })

  onEvent('jei.hide.items', event => {
    event.hide('ae2:facade')
    event.hide(`#buddycards:cards`)
    event.hide(`#buddycards:gummy_cards`)
    event.hide(`createdeco:zinc_coin`)
    event.hide(`createdeco:copper_coin`)
    event.hide(`createdeco:brass_coin`)
    event.hide(`createdeco:iron_coin`)
    event.hide(`createdeco:gold_coin`)
    event.hide(`createdeco:netherite_coin`)
    event.hide(`createdeco:cast_iron_coin`)
    event.hide(`createdeco:zinc_coinstack`)
    event.hide(`createdeco:copper_coinstack`)
    event.hide(`createdeco:brass_coinstack`)
    event.hide(`createdeco:iron_coinstack`)
    event.hide(`createdeco:gold_coinstack`)
    event.hide(`createdeco:netherite_coinstack`)
    event.hide(`createdeco:cast_iron_coinstack`)
    event.hide(`kubejs:trade_card_exchange_currencies_a`)
    event.hide(`createdeco:cast_iron_sheet`)
    event.hide(`createdeco:cast_iron_ingot`)
    event.hide(`create_dd:tin_ore`)
    event.hide(`create_dd:deepslate_tin_ore`)
    event.hide(`beyond_earth:nasa_workbench`)
    event.hide(`thermal:steel_coin`)
    event.hide(`thermal:rose_gold_coin`)
    event.hide(`thermal:iron_coin`)
    event.hide(`thermal:copper_coin`)
    event.hide(`thermal:netherite_coin`)
    event.hide(`thermal:tin_coin`)
    event.hide(`thermal:lead_coin`)
    event.hide(`thermal:nickel_coin`)
    event.hide(`thermal:bronze_coin`)
    event.hide(`thermal:electrum_coin`)
    event.hide(`thermal:invar_coin`)
    event.hide(`thermal:constantan_coin`)
    event.hide(`thermal:signalum_coin`)
    event.hide(`thermal:lumium_coin`)
    event.hide(`thermal:enderium_coin`)
    event.hide(`occultism:silver_ore`)
    event.hide(`occultism:silver_ore_deepslate`)
  })